<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-03-23 09:57

$extensionPath = t3lib_extMgm::extPath('ics_od_appstore');
return array(
	'tx_icsodappstore_common' => $extensionPath . 'lib/class.tx_icsodappstore_common.php',
	'tx_icsodappstore_getapplications_command' => $extensionPath . 'opendata/class.tx_icsodappstore_getapplications_command.php',
	'tx_icsodappstore_getauthors_command' => $extensionPath . 'opendata/class.tx_icsodappstore_getauthors_command.php',
	'tx_icsodappstore_getplatforms_command' => $extensionPath . 'opendata/class.tx_icsodappstore_getplatforms_command.php',
	'tx_icsodappstore_searchapplications_command' => $extensionPath . 'opendata/class.tx_icsodappstore_searchapplications_command.php',
	'tx_icsodappstore_application_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsodappstore_application_datasource.php',
	'tx_icsodappstore_author_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsodappstore_author_datasource.php',
	'tx_icsodappstore_platform_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsodappstore_platform_datasource.php',
	'tx_icsodappstore_pi1' => $extensionPath . 'pi1/class.tx_icsodappstore_pi1.php',
	'tx_icsodappstore_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icsodappstore_pi1_wizicon.php',
	'tx_icsodappstore_pi2' => $extensionPath . 'pi2/class.tx_icsodappstore_pi2.php',
	'tx_icsodappstore_pi2_wizicon' => $extensionPath . 'pi2/class.tx_icsodappstore_pi2_wizicon.php',
	'tx_icsodappstore_pi3' => $extensionPath . 'pi3/class.tx_icsodappstore_pi3.php',
	'tx_icsodappstore_pi3_wizicon' => $extensionPath . 'pi3/class.tx_icsodappstore_pi3_wizicon.php',
	'tx_icsodappstore_pi4' => $extensionPath . 'pi4/class.tx_icsodappstore_pi4.php',
	'tx_icsodappstore_pi4_wizicon' => $extensionPath . 'pi4/class.tx_icsodappstore_pi4_wizicon.php',
	'tx_icsodappstore_task' => $extensionPath . 'scheduler/class.tx_icsodappstore_task.php',
);
?>