<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-17 15:07

$extensionPath = t3lib_extMgm::extPath('smile_icsoddatastore_license');
return array(
	'tx_smileicsoddatastorelicense_filelink' => $extensionPath . 'Classes/class.tx_smileicsoddatastorelicense_filelink.php',
	'tx_smileicsoddatastorelicense_additionalfieldsmarkers' => $extensionPath . 'hooks/class.tx_smileicsoddatastorelicense_additionalFieldsMarkers.php',
	'tx_smileicsoddatastorelicense_applicationfieldsrendercontrols' => $extensionPath . 'hooks/class.tx_smileicsoddatastorelicense_applicationFieldsRenderControls.php',
	'tx_smileicsoddatastorelicense_applicationfieldsrenderform' => $extensionPath . 'hooks/class.tx_smileicsoddatastorelicense_applicationFieldsRenderForm.php',
);
?>