<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-11-28 10:35

$extensionPath = t3lib_extMgm::extPath('ics_od_dataviz');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_icsoddataviz_datastore' => $extensionPath . 'hook/class.tx_icsoddataviz_datastore.php',
	'tx_icsoddataviz_getdata' => $extensionClassesPath . 'class.tx_icsoddataviz_getdata.php',
);
?>