<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-08-07 15:07

$extensionPath = t3lib_extMgm::extPath('ics_od_datastore');
return array(
	'tx_icsoddatastore_dlfile' => $extensionPath . 'downloadfile/class.tx_icsoddatastore_dlfile.php',
	'tx_icsoddatastore_hitcounter' => $extensionPath . 'downloadfile/class.tx_icsoddatastore_hitcounter.php',
	'tx_icsoddatastore_makelink' => $extensionPath . 'downloadfile/class.tx_icsoddatastore_makelink.php',
	'tx_icsoddatastore_tcafeadmin' => $extensionPath . 'hook/class.tx_icsoddatastore_TCAFEAdmin.php',
	'tx_icsoddatastore_dynflex' => $extensionPath . 'lib/class.tx_icsoddatastore_dynflex.php',
	'tx_icsoddatastore_filecontrol' => $extensionPath . 'lib/class.tx_icsoddatastore_filecontrol.php',
	'tx_icsoddatastore_filemanager' => $extensionPath . 'lib/class.tx_icsoddatastore_filemanager.php',
	'tx_icsoddatastore_recordlist' => $extensionPath . 'lib/class.tx_icsoddatastore_recordlist.php',
	'tx_icsoddatastore_sysfolder' => $extensionPath . 'lib/class.tx_icsoddatastore_sysfolder.php',
	'tx_icsoddatastore_tcahelper' => $extensionPath . 'lib/class.tx_icsoddatastore_tcahelper.php',
	'tx_icsoddatastore_title' => $extensionPath . 'lib/class.tx_icsoddatastore_title.php',
	'tx_icsoddatastore_module1' => $extensionPath . 'mod1/index.php',
	'tx_icsoddatastore_navframe' => $extensionPath . 'mod1/tx_icsoddatastore_navframe.php',
	'tx_icsoddatastore_datastore_getagencies_command' => $extensionPath . 'opendata/class.tx_icsoddatastore_datastore_getagencies_command.php',
	'tx_icsoddatastore_datastore_getdatasets_command' => $extensionPath . 'opendata/class.tx_icsoddatastore_datastore_getdatasets_command.php',
	'tx_icsoddatastore_datastore_getfileformats_command' => $extensionPath . 'opendata/class.tx_icsoddatastore_datastore_getfileformats_command.php',
	'tx_icsoddatastore_datastore_getlicences_command' => $extensionPath . 'opendata/class.tx_icsoddatastore_datastore_getlicences_command.php',
	'tx_icsoddatastore_datastore_searchdatasets_command' => $extensionPath . 'opendata/class.tx_icsoddatastore_datastore_searchdatasets_command.php',
	'tx_icsoddatastore_agency_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsoddatastore_tiers_datasource.php',
	'tx_icsoddatastore_dataset_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsoddatastore_dataset_datasource.php',
	'tx_icsoddatastore_fileformat_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsoddatastore_fileformat_datasource.php',
	'tx_icsoddatastore_licence_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsoddatastore_licence_datasource.php',
	'tx_icsoddatastore_pi1' => $extensionPath . 'pi1/class.tx_icsoddatastore_pi1.php',
	'tx_icsoddatastore_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icsoddatastore_pi1_wizicon.php',
	'tx_icsoddatastore_pi2' => $extensionPath . 'pi2/class.tx_icsoddatastore_pi2.php',
	'tx_icsoddatastore_pi2_wizicon' => $extensionPath . 'pi2/class.tx_icsoddatastore_pi2_wizicon.php',
	'tx_icsoddatastore_pi3' => $extensionPath . 'pi3/class.tx_icsoddatastore_pi3.php',
	'tx_icsoddatastore_pi3_wizicon' => $extensionPath . 'pi3/class.tx_icsoddatastore_pi3_wizicon.php',
	'tx_icsoddatastore_task' => $extensionPath . 'scheduler/class.tx_icsoddatastore_task.php',
);
?>