<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-11-18 14:02

$extensionPath = t3lib_extMgm::extPath('ics_opendata_store');
return array(
	'tx_icsopendatastore_filecontrol' => $extensionPath . 'lib/class.tx_icsopendatastore_filecontrol.php',
	'tx_icsopendatastore_filemanager' => $extensionPath . 'lib/class.tx_icsopendatastore_filemanager.php',
	'tx_icsopendatastore_recordlist' => $extensionPath . 'lib/class.tx_icsopendatastore_recordlist.php',
	'tx_icsopendatastore_sysfolder' => $extensionPath . 'lib/class.tx_icsopendatastore_sysfolder.php',
	'tx_icsopendatastore_module1' => $extensionPath . 'mod1/index.php',
	'tx_icsopendatastore_navframe' => $extensionPath . 'mod1/tx_icsopendatastore_navframe.php',
	'tx_icsopendatastore_pi1' => $extensionPath . 'pi1/class.tx_icsopendatastore_pi1.php',
	'tx_icsopendatastore_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icsopendatastore_pi1_wizicon.php',
);
?>