<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-04-14 09:54

$extensionPath = t3lib_extMgm::extPath('ics_od_categories');
return array(
	'tx_icsodcategories_appstore' => $extensionPath . 'class.tx_icsodcategories_appstore.php',
	'tx_icsodcategories_category_datasource' => $extensionPath . 'opendata/datasource/class.tx_icsodcategories_category_datasource.php',
	'tx_icsodcategories_datastore' => $extensionPath . 'class.tx_icsodcategories_datastore.php',
	'tx_icsodcategories_od_getcategories_command' => $extensionPath . 'opendata/class.tx_icsodcategories_od_getcategories_command.php',
	'tx_icsodcategories_pi1' => $extensionPath . 'pi1/class.tx_icsodcategories_pi1.php',
	'tx_icsodcategories_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icsodcategories_pi1_wizicon.php',
	'tx_icsodcategories_tcafeadmin' => $extensionPath . 'class.tx_icsodcategories_TCAFEAdmin.php',
	'tx_icsodcategories_tools' => $extensionPath . 'lib/class.tx_icsodcategories_tools.php',
);
?>