<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-03-23 09:58

$extensionPath = t3lib_extMgm::extPath('ics_od_stores_rel');
return array(
	'tx_icsodstoresrel_appsdatasets' => $extensionPath . 'hook/class.tx_icsodstoresrel_appsDatasets.php',
);
?>