<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-03-23 09:58

$extensionPath = t3lib_extMgm::extPath('ics_od_core_api');
return array(
	'tx_icsodcoreapi_command' => $extensionPath . 'lib/class.tx_icsodcoreapi_command.php',
	'tx_icsodcoreapi_factory' => $extensionPath . 'api/class.tx_icsodcoreapi_factory.php',
	'tx_icsodcoreapi_logger' => $extensionPath . 'api/class.tx_icsodcoreapi_logger.php',
	'tx_icsodcoreapi_pattern_command' => $extensionPath . 'api/class.tx_icsodcoreapi_pattern_command.php',
	'tx_icsodcoreapi_service' => $extensionPath . 'api/class.tx_icsodcoreapi_service.php',
	'tx_icsodcoreapi_parameter' => $extensionPath . 'lib/class.tx_icsodcoreapi_parameter.php',
	'tx_icsodcoreapi_value' => $extensionPath . 'lib/class.tx_icsodcoreapi_value.php',
	'tx_icsodcoreapi_xmldocfe' => $extensionPath . 'lib/tx_icsodcoreapi_xmldocFE.php',
	'tx_icsodcoreapi_module1_command' => $extensionPath . 'mod1/class.tx_icsodcoreapi_module1_command.php',
	'tx_icsodcoreapi_module1_menu' => $extensionPath . 'mod1/class.tx_icsodcoreapi_module1_menu.php',
	'tx_icsodcoreapi_module1_parameter' => $extensionPath . 'mod1/class.tx_icsodcoreapi_module1_parameter.php',
	'tx_icsodcoreapi_module1_value' => $extensionPath . 'mod1/class.tx_icsodcoreapi_module1_value.php',
	'tx_icsodcoreapi_module1' => $extensionPath . 'mod1/index.php',
);
?>